### PR TITLE
Create bug-template.md

### PR DESCRIPTION
**Pull request by Angelles**
Added a bug template and a directory for templates per https://github.com/thedrdu/realmeye.py/issues/7

### CODE REVIEW

**Review by thedrdu — CHANGES_REQUESTED** [review]
Thanks for the contribution! Looks fine to me, though some changes need to be made first:

1. Any issue templates should be created in the `.github/ISSUE_TEMPLATE/` directory rather than a `templates/`directory(sorry for not specifying this, that's on me). I've gone ahead and created this directory on the `main` branch on the original repository, so you can just run the following to sync up and then update the file location(I think):
    ```
    git remote add upstream git@github.com:thedrdu/realmeye.py.git (if you haven't done this yet)
    git fetch upstream
    git checkout main (if you aren't already on main on your fork)
    git merge upstream/main
    ```
    For more information on syncing a fork you can refer to [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork)
2. You can add some YAML front matter to enhance the aesthetics and categorization of issue templates(see [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository))

**Comment by thedrdu** [comment]
Feel free to ask any questions or propose different changes as well!

**Comment by Angelles** [comment]
Hi @thedrdu, I have made the recommended changes and pushed them to this branch! I synced my fork with your repo before doing so. Please have a look at the changes. 

If there are other templates you need, I can make those as well!

**Review by thedrdu — APPROVED** [review]
Looks good to me! Feel free to add additional templates that might seem necessary, or possibly contribute to other documentation/features entirely!

Thanks for the contribution!

**Pull request merged**
